name: CI

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build-test-lint:
    name:  Test & Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Enable Corepack
        working-directory: ${{ inputs.cwd }}
        run: corepack enable

      - name: Install Dependencies
        run: pnpm install

      - name: Lint
        run: pnpm run lint

      # - name: Test
      #   run: pnpm run test
