name: Publish

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Enable Corepack
        working-directory: ${{ inputs.cwd }}
        run: corepack enable

      # - name: Install Dependencies
      #   run: pnpm install
      # - run: pnpm build

      - name: Prepare repository
        run: git fetch --unshallow --tags

      - name: Create Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pnpm dlx auto shipit
